import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { EDGES_ROOT, ENTITIES_ROOT, listJsonFiles } from "../lib/load.js";
import { validateSourceSnapshot } from "../lib/validate.js";
import { parseLuaTree } from "../lib/lua-tree-parser.js";
import {
  generateTreeEdges,
  generateTreeNodeEntities,
} from "../lib/tree-edge-generator.js";
import { runCliMain } from "../lib/cli.js";

const DOMAIN_MAP = {
  adamant: "arbites",
  broker: "hive_scum",
  ogryn: "ogryn",
  psyker: "psyker",
  veteran: "veteran",
  zealot: "zealot",
};
const TREE_DIR = "scripts/ui/views/talent_builder_view/layouts";

await runCliMain("edges:build", async () => {
  const snapshot = validateSourceSnapshot();
  const sourceRoot = snapshot.source_root;
  const snapshotId = snapshot.id;

  // Load all existing entity IDs (non-tree files) so we can filter
  // belongs_to_tree_node edges that reference talents not yet in ground-truth.
  const existingEntityIds = new Set();
  for (const filePath of listJsonFiles(ENTITIES_ROOT)) {
    // Skip *_tree.json files — those are regenerated by this script.
    if (filePath.endsWith("_tree.json")) continue;
    const records = JSON.parse(readFileSync(filePath, "utf8"));
    for (const record of records) {
      existingEntityIds.add(record.id);
    }
  }

  let totalEdges = 0;
  let totalEntities = 0;
  let totalSkipped = 0;

  for (const [luaPrefix, domain] of Object.entries(DOMAIN_MAP)) {
    const luaRelPath = `${TREE_DIR}/${luaPrefix}_tree.lua`;
    const luaAbsPath = join(sourceRoot, luaRelPath);
    const luaSource = readFileSync(luaAbsPath, "utf8");
    const nodes = parseLuaTree(luaSource);

    const allEdges = generateTreeEdges(nodes, domain, snapshotId);
    const entities = generateTreeNodeEntities(nodes, domain, snapshotId, luaRelPath);

    // Add this run's tree_node entity IDs to the known set.
    const treeNodeIds = new Set(entities.map((e) => e.id));

    // Filter out belongs_to_tree_node edges whose source entity doesn't exist.
    const edges = [];
    let skipped = 0;
    for (const edge of allEdges) {
      if (edge.type === "belongs_to_tree_node") {
        if (!existingEntityIds.has(edge.from_entity_id) && !treeNodeIds.has(edge.from_entity_id)) {
          skipped++;
          continue;
        }
      }
      edges.push(edge);
    }

    const edgesPath = join(EDGES_ROOT, `${domain}.json`);
    writeFileSync(edgesPath, JSON.stringify(edges, null, 2) + "\n");

    const entitiesPath = join(ENTITIES_ROOT, `${domain}_tree.json`);
    writeFileSync(entitiesPath, JSON.stringify(entities, null, 2) + "\n");

    const primaryCount = entities.filter((e) => e.status === "source_backed").length;
    const implicitCount = entities.filter((e) => e.status === "partially_resolved").length;

    let msg = `${domain}: ${edges.length} edges, ${primaryCount} primary nodes, ${implicitCount} implicit nodes`;
    if (skipped > 0) msg += ` (${skipped} edges skipped — missing talent entities)`;
    console.log(msg);

    totalEdges += edges.length;
    totalEntities += entities.length;
    totalSkipped += skipped;
  }

  let summary = `\nTotal: ${totalEdges} edges, ${totalEntities} entities across ${Object.keys(DOMAIN_MAP).length} classes`;
  if (totalSkipped > 0) summary += ` (${totalSkipped} edges skipped)`;
  console.log(summary);
});
